### ISSUE TITLE
Does not cover the object correctly when there are multiple refractions

### ISSUE THREAD

**Issue by alibaraneser** [JanLoebel/json-schema-validation-starter#8]
Hi,

I have two sub relation and doesn't map from schema to object.

Schema

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "data": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "attributes": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "title"
                    ]
                }
            },
            "required": [
                "type",
                "id"
            ]
        }
    },
    "required": [
        "data"
    ]
}
```

DTO

```
@JsonSchemaValidation("book.json")
public class BookDto {
    
    private String title;
    
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
```

Result:
`{
    "title": null
}`

**Comment by alibaraneser** [comment]
@JanLoebel Thanks for quick response, you can see full example with https://easyupload.io/e2m63h, moreover, I added a curl request for test where in base root. (sample-request.txt).

**Comment by eirnym** [comment]
Could you also please to reformat json schema?

**Comment by JanLoebel** [comment]
So I had a short look into your project...

Your request data looks like that:
`{
	"data": {
		"type": "property_documents",
		"id": "8469907",
		"attributes": {
			"title": "https://www.clickdimensions.com/links/TestPDFfile.pdf"
		}
	}
}`

But you're DTO that you should match the request has only a single title attribute. The idea of the project is not to map any data out of the schema, it is only the validation of the data, the mapping is done by spring boot as before. So you should first try to get a mapping working without the json-schema-validation and if that mapping works you can add it to validate the incoming data.

Please reopen the issue if there is an working mapping example and it still not works.
